### ISSUE TITLE
How do you retrieve the CSRF token if not passing it on to a templating engine

### ISSUE THREAD

**Issue by heaversm** [valexandersaulys/tiny-csrf#6]
I am rendering static HTML in my express app - so passing the token along in a variable from express is not an option. How would I set this up / retrieve this in a contact form in that case?

**Comment by valexandersaulys** [comment]
The "raw" token is not actually passed but a different encrypted token. This is then [verified once passed in](https://github.com/valexandersaulys/tiny-csrf/blob/6a463fc0608fe11f1e6e0784a4cdf3c2f692990c/encryption.js#L38). An adversary would need to know your `secret` used at instantiation in order to compromise the cookie. **This is much safer than the original csurf library**.

I'd use something else though if you're very paranoid about security though. 

Closing out.
